version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - db_postgresql:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=devgblanco@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 80:80
    depends_on:
      - postgresdb

volumes:
  db_postgresql:
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=devgblanco@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=gblanco123
  #   ports:
      # - 80:80
    # depends_on:
    #   - postgresdb