version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: dad-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=Dariusteemo.10
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /custom/rabbit/data/:/var/lib/rabbitmq/*
    #     - /custom/rabbit/log/:/var/log/rabbitmq